services:
# Servicio de la API
  api:
    build: . # Le dice a Compose que construya la imagen usando el Dockerfile en la misma carpeta
    container_name: electrica-api
    ports:
      - "8080:8080"
    depends_on: # Le dice a nuestra API que no arranque hasta que la BD esté lista
      - postgres-db
    environment:
      # Pasamos la URL de la BD como variable de entorno
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/electricity_db

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=electricity_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db

  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"


volumes:
  postgres_data:
  mongo_data: