name: CI/CD Pipeline - Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  # --- TRABAJO 1: CONSTRUIR Y SUBIR LA IMAGEN ---
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image # Damos un ID a este paso para poder referenciar su salida
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/electrica-api:${{ github.sha }}

  # --- TRABAJO 2: DESPLEGAR EN KUBERNETES ---
  deploy:
    # Este trabajo necesita que 'build_and_push' termine con éxito
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Configura kubectl para usar las credenciales del clúster
      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # Despliega la nueva imagen en Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/api-deployment api=${{ secrets.DOCKERHUB_USERNAME }}/electrica-api:${{ github.sha }}
          kubectl rollout status deployment/api-deployment